@host = http://localhost:3000

### 1-Login
POST {{host}}/auths/login
Content-Type: application/json

{
  "identifier": "bidder_john",
  "password": "123456"
}

###
@token = {{1-Login.response.body.accessToken}}

### Get Won Orders
GET {{host}}/orders/won
Authorization: Bearer {{token}}

### Get Watchlist
GET {{host}}/watchlists
Authorization: Bearer {{token}}

### Get Products
GET {{host}}/products

### Get Product Detail
GET {{host}}/products/13
Authorization: Bearer {{token}}
